### ISSUE TITLE
Wiring schematics

### ISSUE THREAD

**Issue by 3Nplus1** [nandanhere/PiPyPS2#1]
Hello. Thank you for porting PS2 to python. Can you update your wiring pic. and put pin names for both, PS2 part and PiPy part.
Also can you put more comments on what is the protocol used to communicate (UART, SPI, I2C) with the device.
Thx!

**Comment by nandanhere** [comment]
Hello!
The wiring is the same for both PiPyPs2 and PS2X. I will update the Wiring diagram to include a bit more information. i can see that would be confusing . 
as for the Protocol, from what i have seen it appears to be a SPI interface with the Playstation acting as the master and controller acting as the slave. 
[Here is a similar project with arduino. they explain how the controller communicates with the console](https://acoptex.com/project/276/basics-project-058b-wireless-ps2-controller-lcd1602-i2c-module-at-lex-c/)
If you'd like to propose any changes, a pull request is always welcome :)
