### ISSUE TITLE
Alternative PS2 Joystick for raspberry pi 4

### ISSUE THREAD

**Issue by RagnarokL69** [nandanhere/PiPyPS2#2]
I'm working on a controlled rover and I want to use an alternative PS2 joystick, this one comes with usb connection that's why I can't use the PS2 library code.  How can I do it? I am a beginner in programming

Could I control the rover by connecting the joystick to the pc while connecting to the raspberry pi 4 by VNC server?

**Comment by nandanhere** [comment]
While it is possible, i cant help much on that matter. If you are trying to control the rover wired, yes you could just connect the controller to the pi and use some driver for the controller. If you are trying wireless, it is quite difficult. also if you are trying to control it wirelessly, it doesnt make sense to do it with a server. you will get considerable lag.

**Comment by RagnarokL69** [comment]
Do you know any controller to be able to drive with the ps2 controller? I only find those used with retro pi, but not to control microcontrollers, thanks you for your response

**Comment by nandanhere** [comment]
im afraid i dont. Good luck with your project :)
